from django.urls import path,include
from backend import views
from backend import hodviews
from backend import staffviews
from backend import studentviews

urlpatterns = [
    path('', views.index,name='home'),
    path('admin-login/', hodviews.log_in,name='admin-login'),
    path('accounts/',include('django.contrib.auth.urls')),
    path('staff-login/', staffviews.log_in,name='staff-login'),
    path('student-login/', studentviews.log_in,name='student-login'),
    path('admin-logout/', hodviews.log_out,name='admin-logout'),
    path('admin-home/', hodviews.admin_home,name='admin_home'),
    path('add-staff/', hodviews.add_staff,name='add-staff'),
    path('manage-staff/', hodviews.manage_staff,name='manage-staff'),
    path('edit-staff/<int:id>', hodviews.edit_staff,name='edit-staff'),
    path('add-student/', hodviews.add_student,name='add-student'),
    path('manage-student/', hodviews.manage_student,name='manage-student'),
    path('edit-student/<int:id>', hodviews.edit_student,name='edit-student'),
    path('add-course/', hodviews.add_course,name='add-course'),
    path('manage-course/', hodviews.manage_course,name='manage-course'),
    path('edit-course/<int:id>', hodviews.edit_course,name='edit-course'),
    path('add-subject/', hodviews.add_subject,name='add-subject'),
    path('manage-subject/', hodviews.manage_subject,name='manage-subject'),
    path('edit-subject/<int:id>', hodviews.edit_subject,name='edit-subject'),
    path('manage-session/', hodviews.manage_session,name='manage-session'),
    path('check_email_exists/', hodviews.check_email_exists,name='check_email_exists'),
    path('check_username_exists/', hodviews.check_username_exists,name='check_username_exists'),
    path('staff_message_reply/', hodviews.staff_message_reply,name='staff_message_reply'),
    path('student_message_reply/', hodviews.student_message_reply,name='student_message_reply'),
    path('staff_message_reply_get/', hodviews.staff_message_reply_get,name='staff_message_reply_get'),
    path('student_message_reply_get/', hodviews.student_message_reply_get,name='student_message_reply_get'),
    path('student_leave/', hodviews.student_leave,name='student_leave'),
    path('student_leave_approve/<int:id>', hodviews.student_leave_approve,name='student_leave_approve'),
    path('student_leave_reject/<int:id>', hodviews.student_leave_reject,name='student_leave_reject'),
    path('staff_leave/', hodviews.staff_leave,name='staff_leave'),
    path('staff_leave_approve/<int:id>', hodviews.staff_leave_approve,name='staff_leave_approve'),
    path('staff_leave_reject/<int:id>', hodviews.staff_leave_reject,name='staff_leave_reject'),
    path('admin_personal_info/', hodviews.admin_personal_info,name='admin_personal_info'),
    path('edit_admin_personal_info/', hodviews.edit_personal_info,name='edit_admin_personal_info'),
    path('send_staff_notification/', hodviews.send_staff_notification,name='send_staff_notification'),
    path('staff_all_notification/', staffviews.staff_all_notification,name='staff_all_notification'),
    path('student_all_notification/', studentviews.student_all_notification,name='student_all_notification'),
    path('send_student_notification/', hodviews.send_student_notification,name='send_student_notification'),
    path('send_student_message/', hodviews.send_student_message,name='send_student_message'),
    path('send_staff_message/', hodviews.send_staff_message,name='send_staff_message'),
    path('staff-home/', staffviews.staff_home,name='staff_home'),
    path('staff_personal_info/', staffviews.staff_personal_info,name='staff_personal_info'),
    path('edit_staff_personal_info/', staffviews.edit_personal_info,name='edit_staff_personal_info'),
    path('student-home/', studentviews.student_home,name='student-home'),
    path('student-login/', studentviews.log_in,name='student-login'),
    path('student_personal_info/', studentviews.student_personal_info,name='student_personal_info'),
    path('edit_student_personal_info/', studentviews.edit_personal_info,name='edit_student_personal_info'),
    path('take-attendance/', staffviews.take_attendance,name='take_attendance'),
    path('view-attendance-staff/', staffviews.view_attendance,name='view_attendance_staff'),
    path('view-attendance-student/', studentviews.view_attendance,name='view_attendance_student'),
    path('view-attendance-student-data/', studentviews.view_attendance_data,name='view_attendance_student_data'),
    path('fetch_attendance_date/', staffviews.fetch_attendance_date,name='fetch_attendance_date'),
    path('get_students/', staffviews.get_students,name='get_students'),
    path('fetch_students/', staffviews.fetch_students,name='fetch_students'),
    path('save_attendance/', staffviews.save_attendance,name='save_attendance'),
    path('save_attendance_report/', staffviews.save_attendance_report,name='save_attendance_report'),
    path('staff_apply_leave/', staffviews.staff_apply_leave,name='staff_apply_leave'),
    path('staff_fcm_token_save/', staffviews.staff_fcm_token_save,name='staff_fcm_token_save'),
    path('student_apply_leave/', studentviews.student_apply_leave,name='student_apply_leave'),
    path('firebase-messaging-sw.js/', views.showfirebasejs,name='showfirebasejs'),
    path('student_fcm_token_save/', studentviews.student_fcm_token_save,name='student_fcm_token_save'),
    path('feedback/', staffviews.feedback,name='feedback'),
    path('student_result/', staffviews.student_result,name='student_result'),
    path('add_student_result/', staffviews.add_student_result,name='add_student_result'),
    path('save_student_result/', staffviews.save_student_result,name='save_student_result'),
    path('edit_student_result/', staffviews.edit_student_result,name='edit_student_result'),
    path('get_student_for_result/', staffviews.get_student_for_result,name='get_student_for_result'),
    path('fetch_student_result/', staffviews.fetch_student_result,name='fetch_student_result'),
    path('save_edited_student_result/', staffviews.save_edited_student_result,name='save_edited_student_result'),
    path('feedback-student/', studentviews.feedback_student,name='feedback_student'),
    path('view_results/', studentviews.view_results,name='view_results'),
    path('staff-logout/', staffviews.log_out,name='staff-logout'),
    path('student-logout/', studentviews.log_out,name='student-logout'),
]